/* -------------------------------- COMPONENT ------------------------------- */
/* COMPONENT - INPUTS */
export const IMAGE_INPUT_CREATED = "IMAGE_INPUT_CREATED";
export const IMAGE_INPUT_UPDATED = "IMAGE_INPUT_UPDATED";
export const INPUT_CREATED = "INPUT_CREATED";
export const INPUT_DELETED = "INPUT_DELETED";
export const INPUT_UPDATED = "INPUT_UPDATED";

/* COMPONENT - MENUS */
export const EXTERNAL_CLICK = "EXTERNAL_CLICK";
export const MENU_CLOSED = "MENU_CLOSED";
export const MENU_OPENED = "MENU_OPENED";

/* COMPONENT - MODALS */
export const MODAL_CLOSED = "MODAL_CLOSED";
export const MODAL_OPENED = "MODAL_OPENED";

/* COMPONENT - MULTI SELECT */
export const MULTI_SELECTS_UNSELECTED = "MULTI_SELECTS_UNSELECTED";

/* COMPONENT - OBSERVERS */
export const OBSERVER_CREATED = "OBSERVER_CREATED";
export const OBSERVER_DELETED = "OBSERVER_DELETED";
export const OBSERVER_UPDATED = "OBSERVER_UPDATED";

/* COMPONENT - PANELS */
export const PANEL_CREATED = "PANEL_CREATED";
export const PANEL_DELETED = "PANEL_DELETED";
export const PANEL_UPDATED = "PANEL_UPDATED";

/* COMPONENT - TAGGER */
export const TAG_ADDED = "TAG_ADDED";
export const TAG_REMOVED = "TAG_REMOVED";
export const TAG_INPUT_CREATED = "TAG_INPUT_CREATED";
export const TAG_INPUT_UPDATED = "TAG_INPUT_UPDATED";

/* ---------------------------------- DATA ---------------------------------- */
/* DATA - ACCOUNT */
export const ACCOUNT_RETRIEVED = "ACCOUNT_RETRIEVED";
export const PROFILE_UPDATED = "PROFILE_UPDATED";

/* DATA - BOOKMARKS */
export const BOOKMARK_CREATED = "BOOKMARK_CREATED";
export const BOOKMARK_EDITED = "BOOKMARK_EDITED";
export const BOOKMARKS_DELETED = "BOOKMARKS_DELETED";
export const BOOKMARKS_FILTERED = "BOOKMARKS_FILTERED";
export const BOOKMARKS_RETRIEVED = "BOOKMARKS_RETRIEVED";
export const BOOKMARK_SELECTED = "BOOKMARK_SELECTED";
export const BOOKMARKS_UNSELECTED = "BOOKMARKS_UNSELECTED";
export const BOOKMARK_VIEWED = "BOOKMARK_VIEWED";
export const TAGS_UPDATED = "TAGS_UPDATED";

/* DATA - RESET STATE */
export const RESET = "RESET";